version: '3'
services:
  producer:
    build: ./producer
    ports:
      - "5000:5000"  # Example: expose port 5000 for communication with the producer
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=true
  consumer_one:
    build: ./consumer1
    depends_on:
      - rabbitmq
    ports:
      - "5001:5001"
    environment:
      - CONSUMER_ID=1
      - PRODUCER_ADDRESS=http://producer:5000

  consumer_two:
    build: ./consumer2
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "5002:5002"
    environment:
      - CONSUMER_ID=2
      - PRODUCER_ADDRESS=http://producer:5000

  consumer_three:
    build: ./consumer3
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "5003:5003"
    environment:
      - CONSUMER_ID=3
      - PRODUCER_ADDRESS=http://producer:5000

  consumer_four:
    build: ./consumer4
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "5004:5004"
    environment:
      - CONSUMER_ID=4
      - PRODUCER_ADDRESS=http://producer:5000

  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
    - RABBITMQ_DEFAULT_USER=Saanchita
    - RABBITMQ_DEFAULT_PASS=Skanda&2008
    ports:
      - "5673:5672"  # Expose RabbitMQ default port for communication
      - "15673:15672"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: students
    ports:
      - "3308:3308"  # Expose MySQL default port for communication



